# config
cover: /img/img-bg.jpg
logo: /img/logo.svg
bio: In pursuit of breaking knowledge and speed barriers. 

# Content
excerpt_link: Read More

# Header  nav
menu:
  Home: /
  Archive: /archive
  Images: /images
  Wiki: /wiki/2014-10-28-wiki/
  Favorites: /favorites
  Contact: /log/contact/

##Private: /private

# nav.fonticon.css
navclass:
  Home: icon-home
  Archive: icon-news
  Images: icon-image
  Wiki: icon-wiki
  Favorites: icon-Favorites
  Contact: icon-mail

##Private: icon-lock
rss: /atom.xml

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
